### ISSUE TITLE
Sphinx Documentation w. Python V3.12

### ISSUE THREAD

**Issue by hefl99** [itom-project/itom#281]
Itom Documentation does not build with latest Python V3.12 due to package conflict w. breathe v4.35.0.
This installs also sphinx v.7.3.5, but leads to interface conflict since ASTParameterQualifiers seems to be discontinued.
Fixed it temporarily by downgrading sphinx to v5.3.0 and numpydoc to v1.6.0.

This is a mayor issue for future ITOM_Release, but it seems to be noticed by the breathe develoers.

A ticket has been raised recently.
https://github.com/breathe-doc/breathe/issues/981

Action:
Change File "build_documentation.rst" to include latets workaround

**Comment by photoniker** [comment]
My latest docu build was successful with Sphinx 7.2. 7.3 is quite new... Did you try some other Sphinx Major Version 7?

**Comment by photoniker** [comment]
This issue was fix by Sphinx in version 7.3.6 [Changelog](https://www.sphinx-doc.org/en/master/changes.html ).

I build the docu successfully
![image](https://github.com/itom-project/itom/assets/17592823/08314b83-f6a6-41e4-95e2-0831f120b7c4)

@hefl99 Please try the version 7.3.6 and close this issue, if the build was successfull.
