### ISSUE TITLE
Unittest continuousDataObject2NpArray fail

### ISSUE THREAD

**Issue by photoniker** [itom-project/itom#288]
test_continuousDataObject2NpArray of DataObjectNpConversion fails for Python 3.12, Numpy 1.26. 

![image](https://github.com/itom-project/itom/assets/17592823/49a17038-1a44-418b-b120-9cf8eba942ab)

**Comment by magro11** [comment]
This issue is due to a change in Numpy. If a Numpy array is created from a compatible object of another type (here: a dataObject), Numpy for instance tries to get information about the matrix structure via the optional **__array_struct__** member.

If Numpy is able to create its **np.ndarray** by means of a shallow copy (**copy=False**), the original source object is stored in the base member of the numpy array. For Numpy < 1.23, the **base** member was set to a ref-count incremented version of the original **dataObject**. For Numpy >= 1.23, the **base** member is now a tuple, that consists of the ref-count incremented **dataObject** (1st item) and the "PyCapsule" object as 2nd item.

For more information see:

* https://github.com/numpy/numpy/issues/20673
* https://github.com/numpy/numpy/commit/a9299febc1852d3615ac39e88aabb22777120dbb

The unittest in itom will be adapted with a version-switch for the numpy version.
